version: '3.8'

services:
  langgraph-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rca_poc
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace # This mounts everything including notebooks
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
